name: Build Conda Package

on: [ push ]

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Step_1
        uses: ./ # Uses an action in the root directory
        id: action-check-tags-in-another-repo
        with:
          other-repo-name: OSKAR
          other-repo-owner: OxfordSKA
      - name: Step_2
        run: |
          echo steps.Step_1.outputs.tags
