name: Test Action

on: [ push ]

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Step_1
        uses: ./ # Uses an action in the root directory
        id: test
        with:
          other-repo-name: OSKAR
          other-repo-owner: OxfordSKA
    outputs:
      matrix: ${{ steps.test.outputs.tags }}

  job_2:
    needs: job_1

    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ${{ fromJson(needs.job_1.outputs.matrix) }}

    steps:
      - name: Step0
        run: |
          echo from ${{ matrix.tag }}
